### ISSUE TITLE
Issue #1: Configurar ambiente relacional e gerar dados falsos (Henrique)

### ISSUE THREAD

**Issue by BrunoSupriano** [BrunoSupriano/SystemTransportDeltaLake#2]
### Tarefas:
1. **Escolha do banco de dados relacional:**
   - Decidir qual SGBD (Sistema de Gerenciamento de Banco de Dados) será utilizado (por exemplo, MySQL, PostgreSQL, etc.).
   - Configurar o banco de dados escolhido (pode ser localmente ou em um serviço de nuvem).

2. **Criação do esquema de banco de dados:**
   - Definir e criar o esquema do banco de dados com no mínimo 6 tabelas.
   - Garantir que as tabelas principais tenham pelo menos 10.000 linhas cada, com dados distribuídos pelos últimos 3 anos.

3. **Geração de dados falsos:**
   - Utilizar bibliotecas Python como Faker para gerar dados fictícios e popular as tabelas.
   - Certificar-se de que os dados gerados sejam realistas e consistentes entre as tabelas.

4. **Validação dos dados:**
   - Realizar consultas para garantir que os dados estão corretos e distribuídos conforme necessário para os KPIs e métricas futuros.

**Comment by BrunoSupriano** [comment]
@Henrique94

Gostaria que revisasse as tabelas de dados e testasse, ontem verificando com a @JhayneK  #8 tivemos dificuldade em montar as KPIs, utilize os dados ajustados que mandei no csv por último no grupo do wpp. Da uma olhada pois estava vendo que tinha uma certa inconsistencia entre o id usuario e o resto das tabelas.

**Comment by HenriqueSilva29** [comment]
Modelo Relacional do banco

![modelo relacional](https://github.com/BrunoSupriano/SystemTransportDeltaLake/assets/69260698/741333b8-823e-40b5-8b98-a59c13f81970)

**Comment by HenriqueSilva29** [comment]
Arquivos csv com os dados preenchidos.

[Cargas.csv](https://github.com/user-attachments/files/15946126/Cargas.csv)
[Agendamentos.csv](https://github.com/user-attachments/files/15946127/Agendamentos.csv)
[Motoristas.csv](https://github.com/user-attachments/files/15946122/Motoristas.csv)
[Veiculos.csv](https://github.com/user-attachments/files/15946123/Veiculos.csv)
[Rotas.csv](https://github.com/user-attachments/files/15946124/Rotas.csv)
[Clientes.csv](https://github.com/user-attachments/files/15946125/Clientes.csv)

**Comment by jpdarabas** [comment]
Algumas ideias de colunas novas pra adicionar na tabela Agendamentos (que sugiro também a mudança de nome pra Entregas):

* ValorTransporte
* CustoCombustivel
* ConsumoCombustivel
* NumeroParadas
* NivelSatisfacaoCliente 
* NumeroIncidentes 

São só ideias então algumas podem ser descartadas se preferir.

**Comment by jpdarabas** [comment]
Faltou os dados da coluna RestricoesTrafego na tabela Rotas.csv

**Comment by HenriqueSilva29** [comment]
Retirado a coluna restricoesTrafego da tabela Rotas, não vi sentido em mantê-la
