### ISSUE TITLE
Issue #3: Ingestão de Dados no Data Lake (Renato + Diego + João Pedro)

### ISSUE THREAD

**Issue by BrunoSupriano** [BrunoSupriano/SystemTransportDeltaLake#5]
### Tarefas:

Criar notebooks no Databricks para importar os dados CSV da camada Landing.

Desenvolver pipelines que movam os dados da camada Landing para a camada Bronze.

Garantir que os dados sejam carregados de forma eficiente e com controle de qualidade inicial.

**Comment by DiegoHahn** [comment]
Dados injetados com sucesso
