### ISSUE TITLE
Issue #5: Orquestração das tarefas de ingestão e transformação (Diego + Renato)

### ISSUE THREAD

**Issue by BrunoSupriano** [BrunoSupriano/SystemTransportDeltaLake#7]
### Tarefas:

Configurar Databricks Jobs para orquestrar e agendar a execução dos notebooks de ingestão e transformação.

Criar Workflows que definam a ordem de execução e as dependências entre os jobs.

Monitorar a execução dos jobs, ajustando configurações conforme necessário para otimização e controle.

**Comment by DiegoHahn** [comment]
Workflow das tarefas funcionando.
![Captura de tela 2024-06-28 160920](https://github.com/BrunoSupriano/SystemTransportDeltaLake/assets/101281091/861fd331-cd92-4e8a-9ba2-0465e54b3bd7)
