### ISSUE TITLE
Issue #6: Criar dashboard com KPIs e métricas (Jhayne)

### ISSUE THREAD

**Issue by BrunoSupriano** [BrunoSupriano/SystemTransportDeltaLake#8]
### Tarefas:
1. **Escolha da ferramenta de dashboard:**
   - Selecionar uma ferramenta para criar o dashboard (por exemplo, Tableau, Power BI, Metabase, etc.).

2. **Definir KPIs e métricas:**
   - Identificar e definir 4 KPIs e 2 métricas relevantes para o projeto.
   - Documentar as definições e o cálculo de cada KPI e métrica.

3. **Criação do dashboard:**
   - Conectar a ferramenta de dashboard à camada Gold do Data Lake  no DataBriks
   - Criar visualizações para os KPIs e métricas definidos.
   - Garantir que o dashboard tenha um layout claro e fácil de entender, com uma visualização padrão de One Page View.

4. **Testes e validação:**
   - Testar o dashboard para garantir que as visualizações estão corretas e os dados são atualizados conforme esperado.

**Comment by JhayneK** [comment]
1. Escolha da ferramenta de dashboard: Ferramenta de escolha e desenvolvimento do Dashboard foi o PowerBI da Microsoft.

2. Definir KPIs e métricas: Foram utilizadas exemplos de 4 KPI's e 2 métricas para a construção do dashboard exemplo.

3. Criação do dashboard: Foi criado um dashboard exemplo utilizando a ferramenta escolhida.

4. Testes e validação: Iremos iniciar a integração de ferramentas.

**Comment by DiegoHahn** [comment]
Sugestão de KPIs - Números Absolutos

1.Quantos veículos em manutenção:
   -Descrição: Conta o número de veículos que estão atualmente em estado de manutenção.

2. Percentual médio de ocupação dos veículos em relação à sua capacidade:
   - Descrição: Calcula a média percentual de ocupação dos veículos em relação à sua capacidade de carga.

3. Taxa de Motoristas Ativos:
   - Descrição: Indica a porcentagem de motoristas ativos com base nos agendamentos.

4. Número de motoristas ativos:
   - Descrição: Conta quantos motoristas têm CNH ativa com base no status registrado na tabela `Motoristas`.

Sugestão de Métricas - Percentuais e Temporais

1. Entregas dentro do prazo, em um período determinado:
   -Descrição: Calcula o percentual de entregas realizadas dentro do prazo estipulado.

2.Taxa de utilização dos veículos em relação ao período de tempo determinado:
   - Descrição: Calcula a taxa de utilização dos veículos em relação ao tempo de uso disponível, dentro de um período específico.

**Comment by JhayneK** [comment]
Dashboard construído com PowerBI e implementado as 4 KPI's e 2 métricas, sendo estas:

KPI's
1. Contagem dos veículos que estão em manutenção;
2. Contagem de motoristas ativos;
3. Tempo médio de entrega;
4. Entregas futuras (agendadas); 

Métricas
1. Taxa de entrega dentro do prazo;
5. Porcentagem de entrega por tipo de carga no último mês;
