### ISSUE TITLE
Issue #7: Publicar trabalho no GitHub e documentar com MkDocs (Keniel + Bruno +Tiago + Henrique)

### ISSUE THREAD

**Issue by BrunoSupriano** [BrunoSupriano/SystemTransportDeltaLake#9]
### Tarefas:
1. **Publicação do trabalho no GitHub:**
   - Garantir que todos os arquivos e scripts do projeto estejam corretamente versionados e organizados no repositório GitHub.

2. **Configuração do MkDocs:**
   - Configurar o MkDocs com base no arquivo `mkdocs.yml`.
   - Criar a documentação inicial e estruturar as seções conforme necessário.

3. **Documentação detalhada:**
   - Documentar cada parte do projeto (instalação, configuração, execução, etc.) em arquivos `.md` dentro da pasta `docs`.
   - Certificar-se de que a documentação é clara, completa e fácil de seguir.

4. **Gestão de Pull Requests e Issues:**
   - Garantir que todas as alterações sejam submetidas via Pull Request e que sigam um processo de revisão antes de serem mescladas.
   - Organizar as issues no GitHub para acompanhar o progresso e facilitar a colaboração.

5. **Preparação para apresentação:**
   - Preparar um resumo do projeto e uma apresentação em PowerPoint ou similar.
   - Ensaiar a apresentação para garantir que seja clara e concisa dentro dos 20 minutos estipulados.

**Comment by kenielnunes** [comment]
Páginas:

- Índice: apresentação do contexto do trabalho
- Start: comandos para iniciar o projeto
- Pipeline: Comandos e comentários da pipeline completa.
- Dashboard: Demonstração e objetivos do Dashboard.

**Comment by BrunoSupriano** [comment]
Nesse projeto pensei em separarmos dessa forma;

@KenielDev         - Índice: apresentação do contexto do trabalho 
@BrunoSupriano - Start: comandos para iniciar o projeto
@Henrique94          - Pipeline: Comandos e comentários da pipeline completa.
@TiagoS4            - Dashboard: Demonstração e objetivos do Dashboard.

Conversamos mais sobre na call de hoje.

**Comment by HenriqueSilva29** [comment]
Pipeline completa

![Pipeline](https://github.com/BrunoSupriano/SystemTransportDeltaLake/assets/69260698/c4fb03a4-24ea-4e22-84b6-f2b835d61b14)

**Comment by kenielnunes** [comment]
Link da documentação: https://brunosupriano.github.io/SystemTransportDeltaLake

**Comment by kenielnunes** [comment]
Páginas alteradas para:

Home: apresentação do contexto do trabalho
Equipe: integrantes da equipe
Start: comandos para iniciar o projeto
Pipeline: Comandos e comentários da pipeline completa.
Dashboard: Demonstração e objetivos do Dashboard.
